### ISSUE TITLE
[优化]邮箱认证应设置开关或管理后台增加 增删改查 用户的功能

### ISSUE THREAD

**Issue by Jonnyan404** [fantasticit/think#110]
## 1. 问题的表现是怎样的？
强制邮箱认证,增加了用户部署的复杂度,因为这个功能并不是所有人都想要的
## 2. 问题的复现路径
pass
## 3. 预期是什么？
1. 应当设置一个开关来控制是否开启邮箱认证
2. 管理后台增加 增删改查 用户的功能

以上两种方式,均可解决目前的体验问题.

**Comment by yuki070** [comment]
要怎么解？有没有公共的邮箱服务配置？
