### ISSUE TITLE
[FEATURE] 集成excalidraw画布功能

### ISSUE THREAD

**Issue by Jonnyan404** [fantasticit/think#120]
## 请描述功能点
类似window画图功能
## 也可提供功能的实现方案
项目地址: https://github.com/excalidraw/excalidraw

**Comment by fantasticit** [comment]
这开发量看起来不小。。。

**Comment by Jonnyan404** [comment]
> https://github.com/excalidraw/excalidraw

看你规划,可能支持的话,就作为长期规划.
不能的话,直接关闭就好😀

**Comment by fantasticit** [comment]
先不急，这一类和流程图原理类似。先看能不能优化流程图的协作编辑，流程图现在不支持同时编辑，先看能不能优化这个。

**Comment by Jonnyan404** [comment]
> 先不急，这一类和流程图原理类似。先看能不能优化流程图的协作编辑，流程图现在不支持同时编辑，先看能不能优化这个。

嗯嗯,好的.

**Comment by BryantWangGitHub** [comment]
顶一手。。。要是还支持文档block用excalidraw去编排，就无敌了~哈哈
