### ISSUE TITLE
[FEATURE] 导出为Markdown时可选图片和附件

### ISSUE THREAD

**Issue by fox2zz** [fantasticit/think#142]
## 请描述功能点
目前导出为Markdown时，图片和附件都是链接形式，如有防盗链设置，导入本地vuepress，docsify后图片附件无法正常获取。
希望在导出为Markdown时可以同时导出图片和附件（或者设置为可选），也就是可以实现完全离线浏览。

**Comment by fantasticit** [comment]
暂不考虑开发。
