### ISSUE TITLE
[HELP] How to run the project locally ?

### ISSUE THREAD

**Issue by gethari** [fantasticit/think#143]
![image](https://user-images.githubusercontent.com/20477956/182586267-85d07f89-65d8-4524-9309-a71c0b8313d8.png)

When I try to run `docker compose up` I get this error ? Any idea on how to resolve this ?

**Comment by fantasticit** [comment]
Create a prod.yaml file under the [config folder](https://github.com/fantasticit/think/blob/main/config). You can refer to [docker-prod-sample.yaml](https://github.com/fantasticit/think/blob/main/config/docker-prod-sample.yaml) to fill it.

**Comment by fantasticit** [comment]
for local dev, just follow these steps:

```
# first create mysql database and redis
docker run -d --restart=always --name mysql-for-think-dev -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=think -e MYSQL_PASSWORD=think -e MYSQL_DATABASE=think mysql:5.7 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

docker run --name redis-for-think-dev -p 6379:6379 -d redis --appendonly yes --requirepass "root"

# second: install deps and run dev
git clone https://github.com/fantasticit/think.git
cd think
pnpm install
pnpm run dev
```

**Comment by gethari** [comment]
Thanks @fantasticit . It worked flawlessly :) Appreciate your response
