### ISSUE TITLE
[BUG]无法导出流程图、思维导图

### ISSUE THREAD

**Issue by pathing** [fantasticit/think#153]
## 1. 问题的表现是怎样的？
官网https://think.codingit.cn/app/org/FhopEJYP0eFr/wiki/J4JvLihKGFcV/doc/R435Ivh_RQbp，文档导出pdf和word无法导出流程图和思维导图

**Comment by fantasticit** [comment]
这个比较难搞，导出依赖静态 HTML，然而实际上依赖 js 进行绘制。

**Comment by W-Q-Li** [comment]
是不是可以试试，转成静态图片来导出？

**Comment by fantasticit** [comment]
暂不考虑开发。
