### ISSUE TITLE
[BUG]docker-compose在线打包镜像，离线部署api接口地址存在在线环境的地址信息

### ISSUE THREAD

**Issue by zhanghui0** [fantasticit/think#154]
## 1. 问题的表现是怎样的？
docker-compose在线打包镜像，离线部署修改prod.yaml中对应地址后，重启项目后，登录时api接口地址存在在线环境的地址信息
## 2. 问题的复现路径
![image](https://user-images.githubusercontent.com/110993181/183934738-e6ff87fe-fecf-49b8-ad93-542e5d0e2a50.png)
![image](https://user-images.githubusercontent.com/110993181/183935306-09bba72a-ca9c-4170-98d3-09e8130686a7.png)

## 3. 预期是什么？
在任何机器上部署镜像，只需修改对应prod.yaml文件即可正常使用

**Comment by Jonnyan404** [comment]
这不是bug,底层设计如此.  
如果可以改配置就完事了,直接提供镜像不是更香么!
根本就不需要本地再打包构建了.....
