### ISSUE TITLE
[BUG] 通过固定菜单栏插入表格、布局等菜单项无反应

### ISSUE THREAD

**Issue by Ttase** [fantasticit/think#186]
## 1. 问题的表现是怎样的？

点击 “+” 弹出的表格和布局，发现插入不到表格中。

感觉像是点击菜单项的时候，文本输入光标就失效了，导致内容插入不进去：

![image](https://user-images.githubusercontent.com/79624113/189515702-25ac6b1a-8df6-4478-be32-0e047dada94a.png)

但是，通过气泡菜单是可以直接插入表格和布局的：

![image](https://user-images.githubusercontent.com/79624113/189515753-c8987a5b-11e9-4dfc-b225-42339fad1273.png)

## 2. 问题的复现路径

我的浏览器是 windows10、edge 浏览器

**Comment by fantasticit** [comment]
选好以后要点一下。

**Comment by Ttase** [comment]
测试了下，该问题还在。

我在菜单命令这里添加了 console.log 输出信息，发现：并不是每次点击选择表格数量后都会触发插入表格操作！！！

![image](https://user-images.githubusercontent.com/79624113/190942354-881cbf78-2e66-4473-9349-5de9984827cb.png)

**Comment by Ttase** [comment]
感觉是这个表格数量选择框有问题：

![image](https://user-images.githubusercontent.com/79624113/190942838-e385af0f-9c1a-4f90-8259-a0a35de3b52f.png)

![image](https://user-images.githubusercontent.com/79624113/190942865-17256f55-d3ec-4aa0-a444-8680ee092266.png)
