### ISSUE TITLE
绘图的菜单显示异常，而且浏览器和PWA不一样

### ISSUE THREAD

**Issue by kobe651jp** [fantasticit/think#187]
## 1. 问题的表现是怎样的？

**在浏览器**

![image](https://user-images.githubusercontent.com/44263972/190424206-1eef295e-c66b-43f1-8d9e-3e33f69cafb3.png)

**在PWA****

![image](https://user-images.githubusercontent.com/44263972/190424272-376a55c3-91ca-4831-9e69-5f1da392f7ce.png)

使用环境
UBUNTU 22.04 
CHROME 104.0.5112.101（Official Build）

启动浮动菜单时，用什么方法确定所选择的对象是绘图呢？

**Comment by fantasticit** [comment]
editor.isActive('excalidraw')
