### ISSUE TITLE
ddd 与 ioc

### ISSUE THREAD

**Issue by fantasticit** [fantasticit/think#2]
当前项目涉及的实体以及对应关系并不是很多，但是已经存在重复代码及众多接口的前后端认知协同问题，需要重新考虑代码设计。一种可能的设计：
提炼出数据模型的 interface、入参 dto、出参 dto 以及模型操作的抽象接口作为 `@think/model`，前后端各自引入，各自实现对应的 `service`。其中，前端页面可使用 `mobx` 与 `mobx-react` 对接接口实现服务，连接 react view 进行渲染。同时，借助 ioc 让代码整体只关注接口，而不关注具体的方法实现，完成解耦。

**Comment by Huelse** [comment]
Doc search, postgresql or more capability possible?
