### ISSUE TITLE
[BUG] 查找替换出问题

### ISSUE THREAD

**Issue by icode** [fantasticit/think#201]
## 1. 问题的表现是怎样的？
1. 替换无法滚动滚动条追索位置
2. 点击下一个，然后在点替换，选中高亮始终在第一个

## 2. 问题的复现路径
1. 点击下一个
2. 点击替换（不是替换全部）

## 3. 预期是什么？
1. 替换时滚动条跟着动
2. 正确显示高亮位置
3. 替换后光标应该在替换后的位置
4. 存储应该用https://tiptap.dev/guide/custom-extensions#storage来做吧？options总会感觉出问题

**Comment by icode** [comment]
@fantasticit 为什么关闭了？没有修复啊

**Comment by fantasticit** [comment]
我没测试出来。待我周末再看看。

**Comment by icode** [comment]
> 我没测试出来。待我周末再看看。
@fantasticit 
还有一个问题，替换直接就不管用了

https://user-images.githubusercontent.com/972959/203584002-71d4519f-a9f9-4874-aabd-47b345762b6b.mp4

上面视频看红色当前光标位置

下面这个就是替换不起作用的情况

https://user-images.githubusercontent.com/972959/203584130-342afde2-aaa5-4e5a-b4af-2266154173b5.mp4

**Comment by fantasticit** [comment]
ba842033c8f28988173d474bde6f42752792b6ad

**Comment by icode** [comment]
https://think.codingit.cn/ 测试结果还是一样呀

**Comment by icode** [comment]
@fantasticit 测试下来还是一样，上面视频中的问题
