### ISSUE TITLE
[BUG]在手机端微信浏览器，小米10自带的浏览器不能显示页面

### ISSUE THREAD

**Issue by bailin520** [fantasticit/think#202]
## 1. 问题的表现是怎样的？
在手机端微信浏览器，小米10自带的浏览器不能显示页面
## 2. 问题的复现路径
手机微信中打开链接不能显示页面
## 3. 预期是什么？
在各种浏览器中能够显示页面

**Comment by BOKE2014** [comment]
华为也不行

**Comment by fantasticit** [comment]
大概率 jserror。

**Comment by BOKE2014** [comment]
> 大概率 jserror。

作者，这个问题能否修复一下？

**Comment by fantasticit** [comment]
duplicated with #218
