### ISSUE TITLE
[BUG] 感觉搜索文件的时候非常的慢，有考虑使用ElasticSearch操作数据

### ISSUE THREAD

**Issue by suxin1993** [fantasticit/think#215]
## 1. 问题的表现是怎样的？
 搜索文件

## 2. 问题的复现路径
搜索文件等待时长有5s左右

## 3. 预期是什么？
搜索速度加快
 有考虑过通过ElasticSearch操作数据吗
npm i --save @nestjs/elasticsearch @elastic/elasticsearch

**Comment by fantasticit** [comment]
可能是渲染慢了。至于 ES 欢迎PR。
