### ISSUE TITLE
[BUG] 无法在微信中打开

### ISSUE THREAD

**Issue by Degree-21** [fantasticit/think#218]
1.以下是开发者工具打开情况
![image](https://user-images.githubusercontent.com/48709222/207541377-23230574-9320-4574-afa7-933a3f2ea2d5.png)
2.在微信中直接打开白屏，应与开发者报错一致

**Comment by fantasticit** [comment]
1fe8524a8c6b62ae3f3867cf1cfc082aa0d88522

**Comment by fantasticit** [comment]
尝试加载下 `https://unpkg.com/pdfjs-dist@3.1.81/build/pdf.worker.js`，看起来和这个有关。

**Comment by Degree-21** [comment]
是加载这个js吧

**Comment by Degree-21** [comment]
![image](https://user-images.githubusercontent.com/48709222/209311137-5e448fe3-38c3-4aa4-8d1f-c631d541ad36.png)
