### ISSUE TITLE
[BUG]本地dev模式报401错误

### ISSUE THREAD

**Issue by fightingbamboo** [fantasticit/think#241]
## 1. 问题的表现是怎样的？
clone 源码 按照步骤pnpm install 再运行 登录就报错
## 2. 问题的复现路径
按照教程最后
```bash
git clone  https://github.com/fantasticit/think.git
cd think
pnpm install
pnpm run dev
```

访问http://127.0.0.1:5001/  成功
输入账号密码 admin admin 
接口 http://localhost:5002/api/organization/personal  报401错误，接口返回{"statusCode":401,"message":"请登录后使用","success":false,"data":null}
## 3. 预期是什么？
登录成功

**Comment by fantasticit** [comment]
> <img alt="image" width="1511" src="https://user-images.githubusercontent.com/33475775/249190075-3f03b7b8-0730-4c5e-95aa-18b5f3862ac1.png"> 使用docker-compose 搭建也是存在这个问题

麻烦截个完整图片，看不到全部 http 信息。

**Comment by bianlongpeng** [comment]
docker-compose 部署，出现同样的错误，定位不到原因
