### ISSUE TITLE
[FEATURE]使用体验

### ISSUE THREAD

**Issue by hzbb2221** [fantasticit/think#248]
总体下来感觉很不错，体验过后有以下几点小建议
1. 用户管理功能偏弱，貌似目前只能通过数据库管理，可以考虑管理后台功能添加用户管理功能和注册开放/关闭功能。
2. 快速编辑退出，偶尔会导致未自动保存，可以在自动保存的基础上加个手动保存。
3. 思维导图有点难操作，缩放移动困难。

总的来说已经很不错了，我的文档也慢慢迁过来了🤙🤙🤙

**Comment by fantasticit** [comment]
思维导图 https://wanglin2.github.io/mind-map/，不知道这个怎么样，如果可以，打算使用这个。

**Comment by fantasticit** [comment]
> 感谢回复，这个很棒🤙🤙🤙

你们对导图的使用场景多吗？这个目前好像也有点性能问题，我目前觉得 xmind 比较好用。
https://xmind.works/local/JIdmThIR?auth=false
但是这个很难集成。

**Comment by hzbb2221** [comment]
> > 感谢回复，这个很棒🤙🤙🤙
> 
> 你们对导图的使用场景多吗？这个目前好像也有点性能问题，我目前觉得 xmind 比较好用。
> https://xmind.works/local/JIdmThIR?auth=false
> 但是这个很难集成。

大佬，个人比较习惯用思维导图构建知识图谱，我目前也是用xmind，通过超链接跳转至各个知识库。

**Comment by fantasticit** [comment]
在规划私有化部署版本中，脑图会随之重构，请耐心等待，issues 先关闭来。
