### ISSUE TITLE
[BUG]发现一个比较严重的问题，就是复制微信文章的时候，图片不会转成服务器的图片，导致无法显示

### ISSUE THREAD

**Issue by linlongdeng** [fantasticit/think#251]
## 1. 问题的表现是怎样的？
发现一个比较严重的问题，就是复制微信文章的时候，图片不会转成服务器的图片，导致无法显示，有一些文档和CMS是可以做到的，比如语雀，图片自动保存到服务器上。
## 2. 问题的复现路径
随便找一篇微信带图片的文章，复制过去就会出现
## 3. 预期是什么？
微信文章能够带图片直接复制
![云策文档](https://github.com/fantasticit/think/assets/5245310/000baf7e-519c-4f50-b377-87a1b29c53d7)

**Comment by fantasticit** [comment]
```
const { body } = parser.parseFromString(fixHTML(html), 'text/html');
```

思路：遍历 body 中的 img 节点，然后下载图片上传到其他位置并修改 img.src，然后再进行复制。

**Comment by linlongdeng** [comment]
这种确实很不方便，还比如直接从源网页复制图片，不能转成本地图片，只是简单复制链接，一定要把图片下载下来，再复制才能成功。现在很多网站都限制非源网址显示了。
