### ISSUE TITLE
官网无法注册了

### ISSUE THREAD

**Issue by tenglongwentian** [fantasticit/think#267]
官网无法注册了

**Comment by BOKE2014** [comment]
> 官网无法注册了

注册的用户也无法使用了？

**Comment by BOKE2014** [comment]
> 服务器问题，磁盘不太够，扩容略贵。

说句心里话，这么好的东西不再开发真的可惜了

**Comment by fantasticit** [comment]
这两年行情不好，我没有太多时间了。独立编辑器仓库已经在开发了，目前进展略慢。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月18日 10:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [fantasticit/think] 官网无法注册了 (Issue #267) |

服务器问题，磁盘不太够，扩容略贵。

说句心里话，这么好的东西不再开发真的可惜了

**Comment by fantasticit** [comment]
https://www.npmjs.com/search?q=sailkit

定位基于 tiptap，但提供 UI 交互能力，并导出相应函数，让第三方可以自主使用开发。

**Comment by BOKE2014** [comment]
> https://www.npmjs.com/search?q=sailkit
> 
> 定位基于 tiptap，但提供 UI 交互能力，并导出相应函数，让第三方可以自主使用开发。

牛🐮

**Comment by fantasticit** [comment]
三层设计，prosemirror/tiptap –> sailkit –> 业务支撑。这两年行情太差，精力有限



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月23日 15:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [fantasticit/think] 官网无法注册了 (Issue #267) |

https://www.npmjs.com/search?q=sailkit

定位基于 tiptap，但提供 UI 交互能力，并导出相应函数，让第三方可以自主使用开发。

大佬是不是打算参考，affine和Blocksuit的做法？Blocksuit是一个独立的editor而affine是基于“Blocksuit”的知识库系统？真心觉得这个项目停止开发太可惜了其实80%是拿起来就可以用的。

**Comment by fantasticit** [comment]
服务器已修复。证书需要3月换一次。
