### ISSUE TITLE
[BUG]下载@types/cron之后编译报错Cannot find type definition file for 'cron'.

### ISSUE THREAD

**Issue by coding-nothing** [fantasticit/think#272]
## 1. 问题的表现是怎样的？
下载@types/cron之后编译报错Cannot find type definition file for 'cron'.
## 2. 问题的复现路径
执行pnpm  run dev

## 3. 预期是什么？
成功运行

**Comment by fantasticit** [comment]
1. 删除 server 依赖 @types/cron
2. 升级 server typescript 到 4.8.4 以上
3. 修改 server tsconfig.json compileOptions skipLibCheck
