### ISSUE TITLE
[BUG]Failed to compile 

### ISSUE THREAD

**Issue by lionM** [fantasticit/think#277]
## 1. 问题的表现是怎样的？
[client] wait  - compiling / (client and server)...
[client] error - ../../node_modules/.pnpm/@douyinfe+semi-foundation@2.62.1/node_modules/@douyinfe/semi-foundation/lib/cjs/markdownRender/foundation.js:8:0
[client] Module not found: ESM packages (@mdx-js/mdx) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
[client] 
[client] Import trace for requested module:
[client] ../../node_modules/.pnpm/@douyinfe+semi-ui@2.62.1_react-dom@17.0.2_react@17.0.2/node_modules/@douyinfe/semi-ui/lib/cjs/markdownRender/index.js
[client] ../../node_modules/.pnpm/@douyinfe+semi-ui@2.62.1_react-dom@17.0.2_react@17.0.2/node_modules/@douyinfe/semi-ui/lib/cjs/index.js
[client] ./src/pages/index.tsx
[client] 
[client] https://nextjs.org/docs/messages/module-not-found
[client] wait  - compiling /_error (client and server)...
[client] error - ../../node_modules/.pnpm/@douyinfe+semi-foundation@2.62.1/node_modules/@douyinfe/semi-foundation/lib/cjs/markdownRender/foundation.js:8:0
[client] Module not found: ESM packages (@mdx-js/mdx) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
[client] 
[client] Import trace for requested module:
[client] ../../node_modules/.pnpm/@douyinfe+semi-ui@2.62.1_react-dom@17.0.2_react@17.0.2/node_modules/@douyinfe/semi-ui/lib/cjs/markdownRender/index.js
[client] ../../node_modules/.pnpm/@douyinfe+semi-ui@2.62.1_react-dom@17.0.2_react@17.0.2/node_modules/@douyinfe/semi-ui/lib/cjs/index.js
[client] ./src/pages/index.tsx
[client] 
[client] https://nextjs.org/docs/messages/module-not-found

## 2. 问题的复现路径
centos8/windows 10
node: 16.20.2
pnpm:8.15.8

pnpm run dev 
[client] event - compiled client and server successfully in 12.1s (235 modules)

浏览器请求 http://localhost:5001 报错

**Comment by fantasticit** [comment]
使用 2.61.0 版本的 douyinfe/semi-ui
