### ISSUE TITLE
[BUG] 打开知识库, 报RangeError: Adding different instances of a keyed plugin (plugin$)

### ISSUE THREAD

**Issue by kuanghomCheng1995** [fantasticit/think#278]
![image](https://github.com/user-attachments/assets/d4cce930-06a0-460a-bebe-cc1aebd74cab)
## 1. 问题的表现是怎样的？
无法进入知识库页面

## 2. 问题的复现路径
登录后, 先择组织, 创建知识库, 打开新建的知识库, 就会报这个错

## 3. 预期是什么？
正常进入知识库页面

**Comment by xiaoyangyijiu** [comment]
我也遇到了这个问题，求解

**Comment by xiaoMENG1122** [comment]
+1
