### ISSUE TITLE
源码编辑和目录编号

### ISSUE THREAD

**Issue by gray0128** [fantasticit/think#43]
感谢作者！

希望能增加源码编辑模式，以及一键为目录增加编号功能

**Comment by fantasticit** [comment]
不太理解，能详细说下你说的模式和功能吗？

**Comment by gray0128** [comment]
- 目录编号是指一键为目录增加编号功能。假设有一个一键编号的按钮，点击之后，给所有标题增加编号。每次点击都基于当前文档更新编号
- 效果与这个vs插件一致 [markdown-index-pro](https://marketplace.visualstudio.com/items?itemName=chenjun.markdown-index-pro)
- 因为不同层级的标题区分度不是很明显，加上编号后上下文结构和层级关系更清晰
