### ISSUE TITLE
流程图：渲染卡顿，编辑器加载缓慢

### ISSUE THREAD

**Issue by fantasticit** [fantasticit/think#45]
流程图目前的实现是依赖 [drawio 的 viewer.min.js](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/viewer.min.js) 进行渲染，通过 `https://embed.diagrams.net/` 进行编辑，数据通信通过 `postMessage`。不仅渲染卡顿，同时编辑器加载速度也慢，影响体验。

方案一：整合 [mxgraph](https://github.com/jgraph/mxgraph/tree/master/javascript) 的代码，工程量较大，且代码改造也有一定成本。

更好的方案？

**Comment by fantasticit** [comment]
采用方案一。

**Comment by GlodenBoy** [comment]
可以试试阿里的 g6 ?  不过比较原始，可以自己封装一下

**Comment by fantasticit** [comment]
g6 的方案有些原始，封装开发量太大。同时 mxgraph 的方案很成熟（参考 drawio），目前来看还是 mxgraph 最合适，已经整合开发完成。
