### ISSUE TITLE
按照操作说明书，无法运行，报一堆问题

### ISSUE THREAD

**Issue by zhangxweb** [fantasticit/think#46]

**Comment by zhangxweb** [comment]
运行pnpm run build，无法成功编译

**Comment by fantasticit** [comment]
贴图。

**Comment by zhangxweb** [comment]
![image](https://user-images.githubusercontent.com/20125249/169514643-29825cb7-f87c-41cb-9de2-592d7482c6ea.png)

**Comment by fantasticit** [comment]
你试下把  packages/domains/package.json 中的 build 命令改为 `tsc src/*.ts --outDir lib --skipLibCheck --declaration --lib ES6` ，看下是否还报错。

**Comment by zhangxweb** [comment]
![image](https://user-images.githubusercontent.com/20125249/169725391-44830168-d2f3-450c-9b27-1d6c0df4e83b.png)
大佬，还是有问题~

**Comment by fantasticit** [comment]
> ![image](https://user-images.githubusercontent.com/20125249/169725391-44830168-d2f3-450c-9b27-1d6c0df4e83b.png)
> 
> 大佬，还是有问题~

错误信息已经指明了，生产环境需要 prod.yaml 文件，在 config 目录下参考 dev.yaml 新建 prod.yaml 出来再打包。prod.yaml 中的配置是真实上线所需的，所以需要自己新建，而且被 git 忽略。

**Comment by zhangxweb** [comment]
![1653273651(1)](https://user-images.githubusercontent.com/20125249/169733194-e4d87d55-0b36-46d7-a17c-9ac0c477ba17.jpg)

各种方法都尝试了一下，还是无法解决SWC的w问题。
解决措施：https://stackoverflow.com/questions/70640773/failed-to-load-swc-binary
求助，是对安装环境有要求吗？
我使用的版本如下图所示：
![image](https://user-images.githubusercontent.com/20125249/169733549-7a81d139-ad54-42b3-bbb1-22f9632a3924.png)

**Comment by zhangxweb** [comment]
已修复，建议在think/packages/client目录下加入**.babelrc**文件，已解决SWC编译问题
文件内容：
{
  "presets": ["next/babel"]
}

**Comment by fantasticit** [comment]
swc 的问题是 next.js 框架的问题，本身是个特性。加了这个 `.babelrc` 就禁用了 swc ，也许有更好的解法。
