### ISSUE TITLE
docker-compose部署教程

### ISSUE THREAD

**Issue by Jonnyan404** [fantasticit/think#52]
已提交PR #53 ,有需要的可自行拉取最新代码执行. 
### 项目作者已合并,请前往项目主页查看教程.

**Comment by fantasticit** [comment]
厉害！

- /path/to/you/dir/config:/app/packages/config/yaml  # 请注意修改 /path/to/you/dir 为云策文档配置文件目录

这里需要注意下，现在已经改成加载项目根目录的 dev.yaml 或者 prod.yaml 了。

**Comment by Jonnyan404** [comment]
> 厉害！
> 
> * /path/to/you/dir/config:/app/packages/config/yaml  # 请注意修改 /path/to/you/dir 为云策文档配置文件目录
> 
> 这里需要注意下，现在已经改成加载项目根目录的 dev.yaml 或者 prod.yaml 了。

不要不要不要放在根目录,不然配置文件没法单独映射出来,不方便 docker 挂载修改配置配件.

**Comment by fantasticit** [comment]
放在 `packages/config/yaml` 下太深了。在根目录新建 `config` 文件夹存放 yaml 配置？

**Comment by Jonnyan404** [comment]
> 放在 `packages/config/yaml` 下太深了。在根目录新建 `config` 文件夹存放 yaml 配置？

可以的,只要是单独一个目录就行.

**Comment by Jonnyan404** [comment]
> 放在 `packages/config/yaml` 下太深了。在根目录新建 `config` 文件夹存放 yaml 配置？

另外请问你那个生产环境怎么玩?  build之后,还可以依赖外部配置文件吗? build之后,build之前的各种依赖是否可以删掉?

**Comment by Jonnyan404** [comment]
> > 放在 `packages/config/yaml` 下太深了。在根目录新建 `config` 文件夹存放 yaml 配置？
> 
> 另外请问你那个生产环境怎么玩? build之后,还可以依赖外部配置文件吗? build之后,build之前的各种依赖是否可以删掉?
我不太懂nodejs

**Comment by fantasticit** [comment]
`node_modules`、`package.json`、`next.config.js` 、`nest-cli.json` 不可以删，我后面写个脚本，把生产环境所需的文件统一输出到 `output` 目录。

**Comment by Jonnyan404** [comment]
> `node_modules`、`package.json`、`next.config.js` 、`nest-cli.json` 不可以删，我后面写个脚本，把生产环境所需的文件统一输出到 `output` 目录。

好的

**Comment by Jonnyan404** [comment]
> `node_modules`、`package.json`、`next.config.js` 、`nest-cli.json` 不可以删，我后面写个脚本，把生产环境所需的文件统一输出到 `output` 目录。

我发现必须在build之前就修改api接口相关的IP,否则就算后面改了配置文件,配置也不生效了. 是设计如此吗?

**Comment by fantasticit** [comment]
因为配置读取依赖文件读取能力，但是前端在运行时是没有这个能力的，所以目前是打包时注入环境变量，体现为打包后的前端代码里相关配置都已是常量注入。[见 define-plugin](https://www.webpackjs.com/plugins/define-plugin/)

**Comment by Jonnyan404** [comment]
> 见 define-plugin

好的,懂了,在改了,稍等提个pr上来.

**Comment by Jonnyan404** [comment]
@fantasticit 再请教一下,那个jwt如何生成? 有什么要求吗?

**Comment by fantasticit** [comment]
就是加盐，不改也没多大影响。

**Comment by Jonnyan404** [comment]
> 就是加盐，不改也没多大影响。

ok,已提交PR+使用说明+优化首页说明文档.

**Comment by Jackiexiao** [comment]
可以考虑 github ci 自动将编译好的 docker 上传到 dockerhub 中，这样用户可以不用从头编起

**Comment by Jonnyan404** [comment]
> Jackiexiao

不考虑,不支持!

**Comment by Jonnyan404** [comment]
> 可以考虑 github ci 自动将编译好的 docker 上传到 dockerhub 中，这样用户可以不用从头编起

不考虑,不支持!

**Comment by Jackiexiao** [comment]
哦...构建镜像有个参数是 填ip & 域名 的 `EIP`... 这样我构建的镜像就只能自己用了
