### ISSUE TITLE
ssr 能力

### ISSUE THREAD

**Issue by fantasticit** [fantasticit/think#54]
为了激活客户端的服务端渲染能力，需要：

1. 服务端鉴权改为 `set-cookie`，客户端就能在 node 端拿到 cookie 进行预请求
2. 通过 node 端预请求，客户端可以第一时间拿到数据进行页面渲染，同时结合第三方库仍可在 csr 阶段进行 focus、offline、background 的请求
3. 客户端使用的 `swr` 不太合适了，可以切换到 `react-query`

可行 demo：

<img width="400" alt="image" src="https://user-images.githubusercontent.com/26452939/169703960-6a621dfb-5dc8-458e-95e2-6ea90a8e4ae4.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/26452939/169703993-edbd3e39-893a-42ea-bffd-e4dc4a2440da.png">

方案：[using-hydration](https://react-query.tanstack.com/guides/ssr#using-hydration)
分支：[cookie-ssr](https://github.com/fantasticit/think/tree/feat/cookie-ssr)

**Comment by TinsFox** [comment]
可以简单分享一下为什么`swr`不合适吗？我正在使用nextjs 写项目，正在使用`swr`

**Comment by fantasticit** [comment]
和 react-query 比较了下，切到 react-query 来完成服务端渲染代码工作量最小。如果继续使用 swr ，支持服务端请求要写不少代码。
