### ISSUE TITLE
文档编辑器，快捷键渲染有问题

### ISSUE THREAD

**Issue by zhangxweb** [fantasticit/think#55]
![image](https://user-images.githubusercontent.com/20125249/169755662-4f30b64e-b65e-4a87-ad5d-1cc7388f1680.png)
如上图所示

**Comment by fantasticit** [comment]
设备信息发一下，这个可能不好复现。

**Comment by zhangxweb** [comment]
![image](https://user-images.githubusercontent.com/20125249/169772787-91078ce9-8ada-45fa-b63a-513ea21b3b1f.png)

**Comment by fantasticit** [comment]
你是百分百复现吗？可以打开控制台截个浏览器窗口的完整图吗？

**Comment by zhangxweb** [comment]
https://user-images.githubusercontent.com/20125249/169783494-9ef694ef-4e96-48df-bced-7fb12843e3fd.mp4

**Comment by fantasticit** [comment]
收到，不过我还是不能复现（手上只有 win10 笔记本、mac 笔记本），所以要解决这个问题可能需要很久。

**Comment by zhangxweb** [comment]
嗯嗯~   也许是chrome版本太高了，我这边是台式机win10

**Comment by fantasticit** [comment]
我也是这个版本，你是本地启动吗？有没有试过 https://think.codingit.cn/ 这个部署的 demo？

**Comment by Jonnyan404** [comment]
换个浏览器试试,比如 火狐,,,最好是不带各种插件的干净浏览器~~~
