### ISSUE TITLE
建议提供本地文件存储接口

### ISSUE THREAD

**Issue by zhangxweb** [fantasticit/think#57]
![image](https://user-images.githubusercontent.com/20125249/169792183-6d8eae37-2732-46db-ba03-ef4681651e27.png)

**Comment by Jonnyan404** [comment]
假如是内网本地使用,确实很需要 大文件 的本地存储.

提议解决方案参考:

1. 提供本地附件上传+管理相关功能和入口
2. 提供 `minio` 接入方式

**Comment by fantasticit** [comment]
开发成本不大，`server` 的  `file.server.ts`来实现。
