### ISSUE TITLE
上传较大文件时，速度特别慢，建议大文件切片上传

### ISSUE THREAD

**Issue by zhangxweb** [fantasticit/think#58]
参考链接：https://juejin.cn/post/6986188684605259783

**Comment by sang8052** [comment]
嘿!@fantasticit  已经支持 分片上传了哦，但是目前还是通过服务器中转实现的分片上传，故此我正在努力改造，希望能够实现服务器签名，前端直传，回调服务器的方式(似乎不需要回调)呢
