### ISSUE TITLE
文件：更好的文件处理方式

### ISSUE THREAD

**Issue by fantasticit** [fantasticit/think#61]
文件上传作为重要但非核心功能，云策文档不会开发太多，方案上仍旧采用开源（或付费）成熟方案，结合到内部形成多种方案，通过配置决定启用哪种方案。

### 前端

- 文件上传不卡顿
- 文件上传有进度
- 重复文件秒传

### 后端

通过鉴权后，服务器做中转将文件上传到成熟方案上。

## 前端

大文件切片上传，并结合 web-worker 文件 hash 计算。（[see](https://github.com/vercel/next.js/tree/canary/examples/with-web-worker)）。

## 后端

抽象 client 实现，结合实际实现 `uploadFile`、`uploadPart`、`mergePart` 接口。可采用的方案有 [minio](https://docs.min.io/docs/minio-server-configuration-guide.html)、[asw-sdk](https://docs.aws.amazon.com/zh_tw/sdk-for-javascript/v2/developer-guide/welcome.html)、七牛云、阿里云、京东云、腾讯云。

**Comment by fantasticit** [comment]
minio

**Comment by Jonnyan404** [comment]
能减少外部依赖是最好的,也就是自身实现存储+流式播放即可.

**Comment by fantasticit** [comment]
结合开发成本、服务器存储成本和内存成本来看，同时自行开发能力有限。如不满足需求，自行修改 server 端 file.service.ts 即可。

**Comment by ylw8971657** [comment]
可以加个 local 选项，表现为：文件都存储到 `server/static` 目录下，然后结合 express serve static，即可。

**Comment by fantasticit** [comment]
> 可以加个 local 选项，表现为：文件都存储到 `server/static` 目录下，然后结合 express serve static，即可。

这种方式是可行的（对于潜在的服务端压力那就自行承担）。总结一下，目前可能的文本方案：

1. `local`：文件存取都在本地，原理 serve static
2. `minio`：使用方自行部署 minio，server 端调 minio 接口
3. `各种云`：云存储，配合各厂商 sdk 即可

**Comment by fantasticit** [comment]
#65
