### ISSUE TITLE
富文本编辑器能否单独做成一个package呢？

### ISSUE THREAD

**Issue by ununian** [fantasticit/think#62]
最近正在做富文本的选型，感觉这里的比较好用，比直接用 tiptap 会省很多事情，能不能把富文本编辑器抽离成可以单独使用的 package 呢？

**Comment by 2924301751** [comment]
> 最近正在做富文本的选型，感觉这里的比较好用，比直接用 tiptap 会省很多事情，能不能把富文本编辑器抽离成可以单独使用的 package 呢？

目前我也遇到同样的需求，请问您成功剥离了吗？可否交流交流
