### ISSUE TITLE
用docker compose部署后  接口报错

### ISSUE THREAD

**Issue by zz0416** [fantasticit/think#67]
![image](https://user-images.githubusercontent.com/3281481/172140863-9d0058a1-ebbf-49af-9a96-ac924a7955fd.png)

**Comment by fantasticit** [comment]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/26452939/172151520-24e2218c-9dc6-44d8-a21b-15f77b1e5330.png">

检查下配置是否正确。

**Comment by fantasticit** [comment]
#66 可以看下这个 pr 是否能帮助修复。

**Comment by Jonnyan404** [comment]
拉取最新代码,重新构建运行.
然后记得启动前,删除原来映射目录下的配置文件.
或者删除后,再重启一次容器,让新配置自动生成.
