### ISSUE TITLE
是否考虑增加导出Word/PDF/Markdown文档格式

### ISSUE THREAD

**Issue by Rvn0xsy** [fantasticit/think#68]
感谢作者的开源，这个项目体验很好！希望能够增加导出Word/PDF/Markdown文档格式的功能

**Comment by fantasticit** [comment]
- PDF：可参考 [prosemirror-docx](https://github.com/curvenote/prosemirror-docx)

**Comment by Rvn0xsy** [comment]
> * Word：可参考 [prosemirror-docx](https://github.com/curvenote/prosemirror-docx)
> 
> 工作量较大，优先级暂定 P1

感谢你的考虑~！
