### ISSUE TITLE
插入的表格不显示

### ISSUE THREAD

**Issue by v587xpt** [fantasticit/think#70]
1、在插入表格的时候，表格一直不显示，貌似无法正确的插入表格；
2、在两段文本中间，插入代码块时，插入点后面的文本会被放入代码块中；

很不错的一个知识库啊，非常的需要这种开源又好用的知识库，和语雀很像，支持大佬继续开发优化；

**Comment by fantasticit** [comment]
系统版本和浏览器版本提供一下，网页截个图吧。

**Comment by v587xpt** [comment]
不好意思，忘记说明当时的环境了；
我的系统版本：
我的浏览器版本：
当时我并部署，用的是 https://think.codingit.cn/wiki 官网，想先体验一下再进行私有部署的；
我的账号是 v587xpt
反馈的两个问题：
1、在插入表格的时候，表格一直不显示，貌似无法正确的插入表格；
2、在两段文本中间，插入代码块时，插入点后面的文本会被放入代码块中；
在刚才，这两个问题貌似找到了规律；
1、当时我是在代码中间插入的表格（并不是代码块中），可能是检测到了上下行都是代码，在插入表格的时候，迟迟没有显示出现。我测试在文字段落中插入表格是正常显示的；
2、和上面的问题相同，如果上下行都是正常的文字，在两行中间插入代码块时，是正常的；如果附近有代码，就会将代码自动加入到代码块中；


并且，以此也发现另一个问题；
我在两个段落中间敲回车准备换行时，敲击回车键后，上一行的文字加上了下划线，和添加了链接的效果一样，如图：
后来我又测试了几次，找到了规律：如果上一行是个url，尽管它是以文字的形式，不是链接的形式，在它后面回车时，会添加上链接。我不太清楚这是否是一个默认的功能，还是出bug了；




在 2022-06-08 10:39:54，"fantasticit" ***@***.***> 写道：

系统版本和浏览器版本提供一下，网页截个图吧。
