### ISSUE TITLE
docker快速部署后访问5002端口报Provisional headers are shown

### ISSUE THREAD

**Issue by Lrrent** [fantasticit/think#74]
![image](https://user-images.githubusercontent.com/20015265/173609390-ce45111f-918f-418e-a38c-134d2292f791.png)

**Comment by fantasticit** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/26452939/173975687-b559633f-30e2-414a-95f0-0e3bc93d80f0.png">

这里 EIP 参数和 config/prod.yaml 中的配置文件都检查下。
