### ISSUE TITLE
希望可以更全面的支持 markdown 😉

### ISSUE THREAD

**Issue by SongZihui-sudo** [fantasticit/think#75]
希望可以更全面的支持 markdown 。
例如，不可以直接用 markdown 的语法插入链接。  
![image](https://user-images.githubusercontent.com/77034643/173868798-71208db1-6216-4c2a-a199-4cdb4ae4a7e3.png)

**Comment by fantasticit** [comment]
https://user-images.githubusercontent.com/26452939/173975423-09ddecf4-c5a3-478f-acce-693d50223cc2.mov

你是怎么输入的？我测了下没问题。。。

**Comment by SongZihui-sudo** [comment]
链接的名如果是汉字就不行。

**Comment by fantasticit** [comment]
奇怪的 bug 又增加了。 :(_
