### ISSUE TITLE
出现滚动条时页面发生抖动

### ISSUE THREAD

**Issue by weikx** [fantasticit/think#85]
## 1. 问题的表现是怎样的？
编辑文档内容达到一定高度时页面会出现抖动
![BUG-PAGE-SHIFT](https://user-images.githubusercontent.com/31716614/174466645-56921fc3-55c5-47c8-84a5-fc595e144e51.gif)

## 2. 问题的复现路径
如上

## 3. 预期是什么？
文档始终保持同一位置

**Comment by fantasticit** [comment]
内容高度发生了变化，出现滚动条了，可以通过 css 优化？

**Comment by weikx** [comment]
> 内容高度发生了变化，出现滚动条了，可以通过 css 优化？
一个简单的方法是使用 `overflow: overlay`, 不过目前在 [Safari 上不支持](https://caniuse.com/?search=overlay)。

**Comment by weikx** [comment]
看了一下同类产品主要有这三种作法👇🏻
1. 使用 `overflow: overlay`, 不考虑 Safari 等浏览器
2. 始终显示滚动条，这样就不存在这个问题了
3. 不处理，任由闪动

我个人比较倾向使用第一种方法

**Comment by GlodenBoy** [comment]
> 

啊，确实是这样的，不过我之前用的滚动条组件其实是做的始终存在，但是改了样式，看的和没出现一样，滚动条柱子 只在有滚动条 且 鼠标放上去才会出现
