### ISSUE TITLE
[BUG] 使用“/”添加内容时，会丢失当前行的文字

### ISSUE THREAD

**Issue by weikx** [fantasticit/think#86]
## 1. 问题的表现是怎样的？
![BUG-LOST-TEXT](https://user-images.githubusercontent.com/31716614/174469632-20dd1db1-2ab9-4682-a8df-2c2c33d6572e.gif)

## 2. 问题的复现路径
如上

## 3. 预期是什么？
保留当前行文字，新内容另起一行

**Comment by fantasticit** [comment]
这个行为是 toggleNodeType ，相当于 block 转换。

**Comment by weikx** [comment]
> 这个行为是 toggleNodeType ，相当于 block 转换。

不是很理解，那这个行为是符合预期的吗？

**Comment by fantasticit** [comment]
可以改成块状节点另起一行。
