### ISSUE TITLE
使用docker安装报错

### ISSUE THREAD

**Issue by sfzy** [fantasticit/think#88]
npm ERR! code EAI_AGAIN
npm ERR! syscall getaddrinfo
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npm.taobao.org/@nestjs%2fcli failed, reason: getaddrinfo EAI_AGAIN registry.npm.taobao.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-21T02_57_51_217Z-debug-0.log
The command '/bin/sh -c npm i -g pm2 @nestjs/cli pnpm' returned a non-zero code: 1
ERROR: Service 'thinkdoc' failed to build

另外:EIP设置ip应怎样设置

**Comment by fantasticit** [comment]
@Jonnyan404 能帮忙优化下 docker 配置吗？😏

**Comment by sfzy** [comment]
是的就是网络问题，docker容器内无法访问外网
