### ISSUE TITLE
[BUG]linux系统项目启动客户端依赖错误

### ISSUE THREAD

**Issue by Why1092164058** [fantasticit/think#89]
## 1. 问题的表现是怎样的？
客户端启动报错异常停止，判断是依赖问题
![image](https://user-images.githubusercontent.com/44063775/174758106-bbb99407-506b-455d-884c-6c954eb0ddc8.png)

## 2. 问题的复现路径
![image](https://user-images.githubusercontent.com/44063775/174757991-d8f51bc1-dd76-47d3-81b2-cf65abb8e1a6.png)

## 3. 预期是什么？
预期是正常运行

**Comment by fantasticit** [comment]
在 think/packages/client 目录下加入**.babelrc**文件，解决SWC编译问题

文件内容：
{
"presets": ["next/babel"]
}

**Comment by Why1092164058** [comment]
![image](https://user-images.githubusercontent.com/44063775/174767311-6774c612-c9e4-4337-8571-333b00a8f1e5.png)
已尝试，但并没有解决

**Comment by fantasticit** [comment]
这是第2次收到 swc 问题反馈了（都是 Linux 出问题），这是 next.js 的新特性，也许需要考虑下是否启用这个功能。
