### ISSUE TITLE
[BUG]个人使用体验，问题反馈及建议汇总

### ISSUE THREAD

**Issue by emengweb** [fantasticit/think#90]
之前一直在用Outline处理个人整理的一些资料，今天pull了最新的代码，认真体验了下think wiki，大概使用了80%的功能，发现了一些问题，也有不小的惊喜，感觉假以时日，赶超Outline肯定没问题！

### 发现的问题

* 导入md文档部分内容会缺失
* 思维导图（流程图）等图表编辑时，如果尚有选中的内容，切修改过内容文字，直接点击保存按钮，选中项的更改不会被保存。
* 思维导图图，拖拽非root节点会导致画板迅速飞出可视区域。
* 在其他网页，右键复制图片，粘贴在wiki中，只有第一次复制的图片会被成功粘贴，此后再重复复制其他图片，粘贴到wiki后，被上传并保存的始终都是头一张。
* 在使用"-"生成列表之后，选中列表中部分文字，复制，粘贴，会自动增加“\* ”在粘贴的文字前
* 粘贴图片后，有几率导致“正在上传image中”区域不会自动消失

### 使用建议

* 从网页中粘贴的格式和样式排版无法识别
* 移动端使用体验还可以再优化下
* 希望可以增加Chrome的Web应用，就可以将Web应用添加到内容中
* 导入文档功能，建议增加拖拽区域，方便快速提交文件
* 建议在文档的侧边栏直接支持拖拽排序，目前文档管理操作起来不是很直观，编辑排序后会容易忘记点击提交按钮
* 建议增加星标功能，类似于Outline的文档星标

**Comment by fantasticit** [comment]
十分感谢你的反馈。😁

**Comment by emengweb** [comment]
还有一个奇怪的问题，手机端和PC端同时编辑文档，并没有协同的光标，且只会保存最后有改动的那端的内容；
但，如果在某一端，同时打开两个tab页，编辑同一文档，就可以看到协同者的光标，以及实时的内容修改，不清楚是不是我的配置有问题导致。

**Comment by fantasticit** [comment]
麻烦告知下移动端设备信息、浏览器信息。
PS：移动端体验是个挑战，我暂时没有思路解决，欢迎各位提意见、提思路。

**Comment by emengweb** [comment]
移动端就是Chrome官网浏览器 102.0.5005.78 系统Android 11
桌面是Mac的Chrome浏览器 102.0.5005.115（正式版本） (x86_64)

------------------

ps. 今天折腾了下思源笔记的docker部署，他的编辑器是真不错，对md格式支持很好，可以考虑下是否集成这款编辑器 lute

**Comment by fantasticit** [comment]
编辑器的技术栈强依赖 prosemirror 和 yjs，切换成本太大，开源项目也是刚起步，可以多给点耐心。
另外，推荐一下 craft 这款应用。

**Comment by emengweb** [comment]
会持续关注这个项目的，请问下craft是指craft cms么？找了下，符合这个名称的项目不是很多

fantasticit ***@***.***> 于 2022年6月22日周三 17:20写道：
