### ISSUE TITLE
[FEATURE] 希望流程图能增加drawio的其他“更多图形”功能

### ISSUE THREAD

**Issue by pathing** [fantasticit/think#93]
## 请描述功能点
流程图目前支持的图形比较少，希望可以支持drawio本身的“更多图形”导入更多图形
![image](https://user-images.githubusercontent.com/11513848/174940281-094febce-321f-4bc7-8083-c484ca926050.png)

**Comment by fantasticit** [comment]
see https://github.com/fantasticit/think/issues/97#issuecomment-1199463929
