### ISSUE TITLE
[FEATURE] oss/cos config

### ISSUE THREAD

**Issue by TinsFox** [fantasticit/think#95]
## 请描述功能点

配置里面是有oss/cos的配置可以填写，请问是怎样生效的，在默认的情况下，现在看到的是会存在本地上。
如果没有超级管理员 #63 ，这个功能改如何开启配置呢

## 一些想法
1. 个人觉得超管，或者是系统管理这个身份还是蛮需要的，对于一些系统级别的配置
2. think 的定位是什么？个人还是企业级。如果用户群体是企业的话，现在的一些设计是不能对齐企业组织架构的，也缺少了文件存储功能

**Comment by fantasticit** [comment]
可以在 https://github.com/fantasticit/think/issues/97 讨论功能点，收集到足够信息后，会继续迭代开发。
